# Generated by Django 6.0.7 on 2026-07-31 13:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacionBenefica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('estado_verificacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VERIFICADA', 'Verificada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('documento_verificacion', models.CharField(blank=True, max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('DONANTE', 'Donante'), ('ADMINISTRADOR_SISTEMA', 'Administrador del Sistema')], default='DONANTE', max_length=30)),
                ('codigo_2fa', models.CharField(blank=True, max_length=6, null=True)),
                ('requiere_2fa', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdministradorSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(default='Administración General', max_length=100)),
                ('nivel_acceso', models.CharField(default='TOTAL', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causas', to='donatenow_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20)),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanias', to='donatenow_app.categoria')),
                ('causa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanias', to='donatenow_app.causa')),
                ('objetivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campania', to='donatenow_app.objetivorecaudacion')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanias', to='donatenow_app.organizacionbenefica')),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_donante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_anonima', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='donatenow_app.campania')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='donatenow_app.donante')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaDonaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_donaciones', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('donacion_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('donacion_maxima', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('campania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadistica', to='donatenow_app.campania')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('PAYPAL', 'PayPal')], default='TARJETA_CREDITO', max_length=30)),
                ('titular', models.CharField(max_length=150)),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='donatenow_app.donante')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoRecaudacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_recaudado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cantidad_donaciones', models.PositiveIntegerField(default=0)),
                ('porcentaje_alcanzado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('campania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='donatenow_app.campania')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('hash_verificacion', models.CharField(max_length=64)),
                ('pdf_path', models.CharField(blank=True, max_length=255)),
                ('enviado_email', models.BooleanField(default=True)),
                ('donacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='donatenow_app.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('DONACIONES', 'Reporte de Donaciones'), ('CAMPANIAS', 'Reporte de Campañas'), ('ORGANIZACIONES', 'Reporte de Organizaciones')], max_length=30)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros', models.TextField(blank=True)),
                ('archivo_url', models.CharField(blank=True, max_length=255)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_transaccion', models.CharField(max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_PROCESO', 'En Proceso')], default='EN_PROCESO', max_length=20)),
                ('mensaje_error', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('donacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaccion', to='donatenow_app.donacion')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donatenow_app.metodopago')),
            ],
        ),
    ]
